/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.PricingTierDAO;
import com.essar.dao.ClassMasterDAO;
import com.essar.utils.TableMouseListener;
import com.essar.pojos.ClassMaster;
import com.essar.utils.GenericUtils;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rahumathulla
 */
public class ClassMasterForm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ClassMaster
     */
    int classMasterId=0;
    DefaultTableModel classMasterModel = null;
    public ClassMasterForm() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        mnuCategory = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mitDelete = new javax.swing.JMenuItem();
        mitEdit = new javax.swing.JMenuItem();
        pnlProductCategory = new javax.swing.JPanel();
        lblFees = new javax.swing.JLabel();
        lblClassName = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        txtFees = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        panClassMaster = new javax.swing.JScrollPane();
        tblClassMaster = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        mitDelete.setText("jMenuItem1");

        mitEdit.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Master");
        setName("frmProductCategory"); // NOI18N

        lblFees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFees.setText("Fees");

        lblClassName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClassName.setText("Class Name");

        txtClassName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtFees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblClassMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Name", "Fees", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panClassMaster.setViewportView(tblClassMaster);

        javax.swing.GroupLayout pnlProductCategoryLayout = new javax.swing.GroupLayout(pnlProductCategory);
        pnlProductCategory.setLayout(pnlProductCategoryLayout);
        pnlProductCategoryLayout.setHorizontalGroup(
            pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                                .addComponent(lblClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                                .addComponent(lblFees, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFees, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancel)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panClassMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductCategoryLayout.setVerticalGroup(
            pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductCategoryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFees, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panClassMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(btnSave.getText().equalsIgnoreCase("add")){
            btnSave.setText("Save");
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png")));
            enableFormElements(true);
            //txtReferenceCode.requestFocus();
        }else{
            //Implement Save Logic
            if(validateForm()){             
                
                if(classMasterId>0){
                    updateClassMasterForm();
                    classMasterId=0;
                }
                else{
                    saveClassMasterForm();
                }
                initializeForm();
            }            
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassMasterForm().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        
        //!@--17/03/2020 Refreshing table data
        //tblCategory.removeAll();
        //tblCategory.repaint();
        DefaultTableModel model = (DefaultTableModel) tblClassMaster.getModel();
        model.setRowCount(0);
        
        btnSave.setText("Add");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png")));
        btnSave.requestFocus();
        txtClassName.setText("");
        txtFees.setText("");
     

        enableFormElements(false);
        ClassMasterDAO classMasterDAO = new ClassMasterDAO();
        renderDataIntoTable(classMasterDAO.retrieveAll());
        mnuCategory = new JPopupMenu();
        mitDelete = new JMenuItem("Delete");
        mitDelete.addActionListener(this);
        
        mitEdit = new JMenuItem("Edit");
        mitEdit.addActionListener(this);
        
        mnuCategory.add(mitDelete);
        //mnuCategory.add(mitEdit);
         // sets the popup menu for the table
        tblClassMaster.setComponentPopupMenu(mnuCategory);      
        tblClassMaster.addMouseListener(new TableMouseListener(tblClassMaster));
        
        TableColumn idColumn1 = tblClassMaster.getColumnModel().getColumn(tblClassMaster.getColumnCount()-1);
        idColumn1.setPreferredWidth(0);
        idColumn1.setMinWidth(0);
        idColumn1.setMaxWidth(0);

   
    }
    
    public void enableFormElements(boolean flag){
        txtClassName.setEnabled(flag);
        txtFees.setEnabled(flag);
    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        if(null == txtClassName.getText()){
            JOptionPane.showMessageDialog(null, "The class name "+txtClassName.getText() +" is not valid.");
            return false;
        }
        if(null == txtFees.getText() || !(txtFees.getText().matches("^\\d*\\.\\d+|\\d+|\\d+\\.\\d*$"))){
            JOptionPane.showMessageDialog(null, "Fees value "+txtFees.getText() +" is not valid.");
            return false;
        }
        //txtProductCategoryName.setText("");
        return true;
    }
    
    public void saveClassMasterForm(){ 
        ClassMaster classMaster = new ClassMaster();
        classMaster.setClassName(txtClassName.getText());
        classMaster.setFees(Double.parseDouble(txtFees.getText()));        
        ClassMasterDAO classMasterDAO = new ClassMasterDAO();
        classMasterDAO.insertIntoDB(classMaster);        
    }
    
    public void updateClassMasterForm(){ 
        ClassMaster classMaster = new ClassMaster();
        classMaster.setClassMasterId(classMasterId);
        classMaster.setClassName(txtClassName.getText());
        classMaster.setFees(Double.parseDouble(txtFees.getText()));
        ClassMasterDAO classMasterDAO = new ClassMasterDAO();
        classMasterDAO.updateClassMaster(classMaster);        
    }
    
    public void renderDataIntoTable(List<ClassMaster> classMasterList){
        //DefaultTableModel classMasterModel = null;
        classMasterModel = (DefaultTableModel) tblClassMaster.getModel();
        //System.out.println("-----"+classMasterList.size());
        for(int i=0;i<classMasterList.size();i++){
            classMasterModel.addRow(new Object[]{classMasterList.get(i).getClassName()
                    ,classMasterList.get(i).getFees()
                    ,classMasterList.get(i).getClassMasterId()});
        //model.
        }
        
        tblClassMaster.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {     // to detect doble click events
                    syncDataFromViewToTable();
                }
            }
        });
        
    }
    
    public void syncDataFromViewToTable(){
        ClassMaster classMaster= null;
        System.out.println("--------INSIDE Edit-"+tblClassMaster.getModel().getValueAt(tblClassMaster.getSelectedRow(),0));
        classMasterId = Integer.parseInt(tblClassMaster.getModel().getValueAt(tblClassMaster.getSelectedRow(),tblClassMaster.getColumnCount()-1).toString());
        ClassMasterDAO classMasterDAO = new ClassMasterDAO();
        classMaster = classMasterDAO.retrieveById(classMasterId);

        txtFees.setText(classMaster.getFees()+"");
        txtClassName.setText(classMaster.getClassName());
        enableFormElements(true);
        btnSave.setText("Update");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblFees;
    private javax.swing.JMenuItem mitDelete;
    private javax.swing.JMenuItem mitEdit;
    private javax.swing.JPopupMenu mnuCategory;
    private javax.swing.JScrollPane panClassMaster;
    private javax.swing.JPanel pnlProductCategory;
    private javax.swing.JTable tblClassMaster;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtFees;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();
            if (menu == mitDelete) {
                //int rowIndex = tblCategory.getSelectedRow();
                //System.out.println("--------INSIDE DELETE-"+tblCategory.getModel().getValueAt(tblCategory.getSelectedRow(),0));
                String classMasterCode = tblClassMaster.getModel().getValueAt(tblClassMaster.getSelectedRow(),0).toString();
                ClassMasterDAO classMasterDAO = new ClassMasterDAO();
                classMasterDAO.deleteRecordByCode(classMasterCode);
                //initializeForm();
                GenericUtils.removeRowFromJTable(tblClassMaster, classMasterModel);
            } else if (menu == mitEdit) {
                syncDataFromViewToTable();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
}
