/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.ClassMasterDAO;
import com.essar.dao.GstDAO;
import com.essar.dao.StudentDAO;
import com.essar.dao.SchoolDAO;
import com.essar.dao.StockDAO;
import com.essar.dao.SupplierDAO;
import com.essar.pojos.ClassMaster;
import com.essar.pojos.GST;
import com.essar.pojos.Student;
import com.essar.pojos.School;
import com.essar.utils.ConnectionManager;
import com.essar.pojos.Stock;
import com.essar.pojos.Supplier;
import com.essar.utils.GenericUtils;
import com.essar.utils.QueryStrings;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rahumathulla
 */
public class StudentRegister extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Stock
     */
    long studentIdEdit=0;
    DecimalFormat df = new DecimalFormat("####.##");
    double gTuitionFees=0;
    public StudentRegister() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGender = new javax.swing.ButtonGroup();
        pnlStockEntry = new javax.swing.JPanel();
        lblParent = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtParent = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        lblClass = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblSchoolName = new javax.swing.JLabel();
        cmbSchoolName = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dtpDateOfBirth = new com.toedter.calendar.JDateChooser();
        lblDateOfBirth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        lblClass1 = new javax.swing.JLabel();
        cmbRelationship = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        chkSinging = new javax.swing.JCheckBox();
        chkDancing = new javax.swing.JCheckBox();
        chkMusicalInstruments = new javax.swing.JCheckBox();
        chkCricket = new javax.swing.JCheckBox();
        chkFootBall = new javax.swing.JCheckBox();
        chkVolleyBall = new javax.swing.JCheckBox();
        chkChess = new javax.swing.JCheckBox();
        chkOthers = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTuitionFees = new javax.swing.JTextField();
        lblAdmissionDate = new javax.swing.JLabel();
        dtpAdmissionDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Register");
        setExtendedState(6);

        lblParent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblParent.setText("Parent/Guardian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Student Name");

        txtParent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParentActionPerformed(evt);
            }
        });
        txtParent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtParentKeyPressed(evt);
            }
        });

        txtStudentName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStudentName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtStudentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStudentNameKeyPressed(evt);
            }
        });

        lblClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClass.setText("Relationship");

        cmbClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassActionPerformed(evt);
            }
        });
        cmbClass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbClassKeyPressed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddress.setText("Address");

        txtAddress.setColumns(10);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAddress.setRows(3);
        txtAddress.setTabSize(4);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        lblSchoolName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSchoolName.setText("School Name");

        cmbSchoolName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSchoolName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSchoolNameKeyPressed(evt);
            }
        });

        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        btgGender.add(radMale);
        radMale.setText("Male");
        radMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaleActionPerformed(evt);
            }
        });

        btgGender.add(radFemale);
        radFemale.setText("Female");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radMale)
                .addGap(30, 30, 30)
                .addComponent(radFemale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radMale)
                    .addComponent(radFemale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Gender");

        dtpDateOfBirth.setDateFormatString("dd/MM/yyyy");
        dtpDateOfBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dtpDateOfBirthFocusLost(evt);
            }
        });
        dtpDateOfBirth.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dtpDateOfBirthInputMethodTextChanged(evt);
            }
        });
        dtpDateOfBirth.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtpDateOfBirthPropertyChange(evt);
            }
        });
        dtpDateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtpDateOfBirthKeyPressed(evt);
            }
        });

        lblDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDateOfBirth.setText("Date of Birth");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Contact Number");

        txtContactNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        txtContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactNumberKeyPressed(evt);
            }
        });

        lblClass1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClass1.setText("Class");

        cmbRelationship.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbRelationship.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Father", "Mother", "Step-Father", "Step-Mother", "Silbling", "Grand Father", "Grand Mother", "Uncle", "Aunt", "Others" }));
        cmbRelationship.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbRelationshipKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extra Curricular Skills", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N

        chkSinging.setText("Singing");

        chkDancing.setText("Dancing");

        chkMusicalInstruments.setText("Musical Instruments");

        chkCricket.setText("Cricket");

        chkFootBall.setText("Foot Ball");

        chkVolleyBall.setText("Volley Ball");

        chkChess.setText("Chess");

        chkOthers.setText("Others");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkCricket)
                        .addGap(18, 18, 18)
                        .addComponent(chkFootBall))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkSinging)
                        .addGap(18, 18, 18)
                        .addComponent(chkDancing)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkMusicalInstruments)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkVolleyBall)
                        .addGap(18, 18, 18)
                        .addComponent(chkChess)
                        .addGap(18, 18, 18)
                        .addComponent(chkOthers)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSinging)
                    .addComponent(chkDancing)
                    .addComponent(chkMusicalInstruments))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCricket)
                    .addComponent(chkFootBall)
                    .addComponent(chkVolleyBall)
                    .addComponent(chkChess)
                    .addComponent(chkOthers))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("Save");
        btnSave.setAlignmentY(0.0F);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReports.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnReports.setMnemonic('t');
        btnReports.setText("Students Report");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnViewAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewall.png"))); // NOI18N
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setMnemonic('e');
        btnSearch.setText("Search");
        btnSearch.setEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        btnReset.setMnemonic('R');
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tution Fees");

        txtTuitionFees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTuitionFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuitionFeesActionPerformed(evt);
            }
        });
        txtTuitionFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTuitionFeesKeyPressed(evt);
            }
        });

        lblAdmissionDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAdmissionDate.setForeground(new java.awt.Color(0, 102, 102));
        lblAdmissionDate.setText("Admission Date*");

        dtpAdmissionDate.setForeground(new java.awt.Color(0, 102, 102));
        dtpAdmissionDate.setDateFormatString("dd/MM/yyyy");
        dtpAdmissionDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dtpAdmissionDateFocusLost(evt);
            }
        });
        dtpAdmissionDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dtpAdmissionDateInputMethodTextChanged(evt);
            }
        });
        dtpAdmissionDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtpAdmissionDatePropertyChange(evt);
            }
        });
        dtpAdmissionDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtpAdmissionDateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlStockEntryLayout = new javax.swing.GroupLayout(pnlStockEntry);
        pnlStockEntry.setLayout(pnlStockEntryLayout);
        pnlStockEntryLayout.setHorizontalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStockEntryLayout.createSequentialGroup()
                                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStockEntryLayout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46))
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dtpDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                        .addComponent(lblAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dtpAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)))
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(lblSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStockEntryLayout.createSequentialGroup()
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblParent, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRelationship, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtParent)))
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTuitionFees, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(lblClass1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlStockEntryLayout.setVerticalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClass1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTuitionFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(pnlStockEntry, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtpDateOfBirthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtpDateOfBirthKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB ){
            //txtDisplayName.requestFocus();
        }/*else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtItemName.requestFocus();
        }*/
    }//GEN-LAST:event_dtpDateOfBirthKeyPressed

    private void dtpDateOfBirthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtpDateOfBirthPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpDateOfBirthPropertyChange

    private void dtpDateOfBirthInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dtpDateOfBirthInputMethodTextChanged
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Inside InputMethodTextChanged");
        //showHideCessFields(dtpSalesDate.getDate());
    }//GEN-LAST:event_dtpDateOfBirthInputMethodTextChanged

    private void dtpDateOfBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dtpDateOfBirthFocusLost
        // TODO add your handling code here:
        dtpAdmissionDate.requestFocus();
    }//GEN-LAST:event_dtpDateOfBirthFocusLost

    private void radMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMaleActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        QueryStrings.studentListQuery = "SELECT * from student";
        this.dispose();
        ViewStudents viewStudents = new ViewStudents();
        //studentAlerts.setBounds(40, 40, 940, 500);
        viewStudents.setVisible(true);
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        initializeForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        StockFind studentFind = new StockFind();
        studentFind.setBounds(150, 160, 480, 300);
        studentFind.setVisible(true);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
                String reportQuery = "SELECT st.student_name AS student_name, st.gender AS gender, st.date_of_birth AS dob"
                + ", st.admission_date AS adm_date, st.guardian AS guardian, st.contact_number AS cont_number"
                + ", cl.class_name AS class_name, st.extra_curricular AS extra_curr " 
                + " FROM student st JOIN class_master cl ON st.class_id = cl.class_master_id WHERE 1=1 ";
        GenericUtils.printReport("D:\\Leaders\\reports\\student_report.jrxml", reportQuery);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(btnSave.getText().equalsIgnoreCase("add")){
            radMale.setSelected(true);
            if(null==dtpAdmissionDate.getDate()){
                dtpAdmissionDate.setDate(new Date());
            }
             if(null==dtpDateOfBirth.getDate()){
                Calendar cal = Calendar.getInstance();
                System.out.println("Today : " + cal.getTime());
                cal.add(Calendar.DATE, -365*15);
                System.out.println("30 days ago: " + cal.getTime());
                dtpDateOfBirth.setDate(cal.getTime());

            }
            ClassMasterDAO classMasterDAO = new ClassMasterDAO();
            renderCategoryDataIntoDropDown(classMasterDAO.retrieveAll());

            SchoolDAO schoolDAO = new SchoolDAO();
            renderSupplierDataIntoDropDown(schoolDAO.retrieveAll());

            /*GstDAO gstDAO = new GstDAO();
            renderGstDataIntoDropDown(gstDAO.retrieveAll());*/

            btnSave.setText("Save");
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png")));
            //txtMargin.setText("5");
            //txtReOrderAt.setText("5");
            //chkGstIncluded.setSelected(true);
            enableFormElements(true);
            txtStudentName.requestFocus();
        }else{
            //Implement Save Logic
            if(validateForm()){
                saveStockData();
                initializeForm();
            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbSchoolNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSchoolNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            radMale.requestFocus();
        }
    }//GEN-LAST:event_cmbSchoolNameKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB ){
            radMale.requestFocus();
        }
    }//GEN-LAST:event_txtAddressKeyPressed

    private void cmbClassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbClassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            cmbSchoolName.requestFocus();
        }
    }//GEN-LAST:event_cmbClassKeyPressed

    private void txtStudentNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtAddress.requestFocus();
        }
    }//GEN-LAST:event_txtStudentNameKeyPressed

    private void txtParentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParentKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtStudentName.requestFocus();
        }
    }//GEN-LAST:event_txtParentKeyPressed

    private void txtParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParentActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void txtContactNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberKeyPressed

    private void cmbRelationshipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbRelationshipKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRelationshipKeyPressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            dtpDateOfBirth.requestFocus();
        }
    }//GEN-LAST:event_jPanel2KeyPressed

    private void txtTuitionFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuitionFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuitionFeesActionPerformed

    private void txtTuitionFeesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuitionFeesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuitionFeesKeyPressed

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        // TODO add your handling code here:
        try{
            gTuitionFees = ((ClassMaster)(cmbClass.getSelectedItem())).getFees();
            txtTuitionFees.setText(gTuitionFees+"");
         }catch(Exception e){
            System.out.println("-- "+e.getMessage());
        }
    }//GEN-LAST:event_cmbClassActionPerformed

    private void dtpAdmissionDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dtpAdmissionDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpAdmissionDateFocusLost

    private void dtpAdmissionDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dtpAdmissionDateInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpAdmissionDateInputMethodTextChanged

    private void dtpAdmissionDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtpAdmissionDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpAdmissionDatePropertyChange

    private void dtpAdmissionDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtpAdmissionDateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpAdmissionDateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        studentIdEdit =0;
        btnSave.setText("Add");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png")));
        btnSave.requestFocus();
        //txtHSNCode.setText("");
        txtStudentName.setText("");
        txtParent.setText("");
        txtContactNumber.setText("");
        txtAddress.setText("");
        txtTuitionFees.setText("");
        //chkAddGst.setSelected(false);
        //txtSuggestions.setVisible(false);
        if(cmbClass.getItemCount()>0){
            cmbClass.setSelectedIndex(0); 
        }

        cmbSchoolName.removeAllItems();
        //cmbGST.removeAllItems();
        cmbClass.removeAllItems();
        


        enableFormElements(false);
        SupplierDAO supplierDAO = new SupplierDAO();
        renderDataIntoTable(supplierDAO.retrieveAll());
        /*mnuCategory = new JPopupMenu();
        mitDelete = new JMenuItem("Delete");
        mitDelete.addActionListener(this);
        
        mnuCategory.add(mitDelete);
         // sets the popup menu for the table
        tblSupplier.setComponentPopupMenu(mnuCategory);      
        tblSupplier.addMouseListener(new TableMouseListener(tblSupplier));*/
   
    }
    
    public void enableFormElements(boolean flag){
        txtParent.setEnabled(flag);
        txtAddress.setEnabled(flag);
        txtStudentName.setEnabled(flag);
        txtContactNumber.setEnabled(flag);
        txtParent.setEnabled(flag);
        cmbClass.setEnabled(flag);
        cmbSchoolName.setEnabled(flag);
        cmbRelationship.setEnabled(flag);
        txtTuitionFees.setEnabled(flag);
        dtpAdmissionDate.setEnabled(flag);
        dtpDateOfBirth.setEnabled(flag);

    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        /*if(null == txtParent.getText()){
            JOptionPane.showMessageDialog(null, "Parent Name "+txtParent.getText() +" is not valid.");
            txtParent.requestFocus();
            return false;
        }*/
        if(null == txtStudentName.getText() || txtStudentName.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Item name "+txtStudentName.getText() +" is not valid.");
            txtStudentName.requestFocus();
            return false;
        }
        
        if(cmbSchoolName.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please choose a Supplier Name");
            cmbSchoolName.requestFocus();
            return false;
        }
        
        if(cmbClass.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please choose a Class");
            cmbClass.requestFocus();
            return false;
        }
        if(null == dtpAdmissionDate.getDate()){
            JOptionPane.showMessageDialog(null, "Please select admission date");
            dtpAdmissionDate.requestFocus();
            return false;
        }
        
        
        
        //txtProductCategoryName.setText("");
        return true;
    }
    
    public void saveStockData(){
 
        Student student = new Student();
        String extraCurricular ="";
        student.setStudentName(txtStudentName.getText());
        student.setAddress(txtAddress.getText());
        if(radMale.isSelected())
            student.setGender("M");
        else
            student.setGender("F");
        
        if(chkChess.isSelected())
            extraCurricular+="chess+";
        if(chkCricket.isSelected())
            extraCurricular+="cricket+";
        if(chkFootBall.isSelected())
            extraCurricular+="football+";
        if(chkVolleyBall.isSelected())
            extraCurricular+="volleyball+";

        if(chkSinging.isSelected())
            extraCurricular+="singing+";
        if(chkDancing.isSelected())
            extraCurricular+="dancing+";
        if(chkMusicalInstruments.isSelected())
            extraCurricular+="musicalinstruments+";
        if(chkOthers.isSelected())
            extraCurricular+="others+";
        
        
        student.setDateOfBirth(dtpDateOfBirth.getDate());
        student.setAdmissionDate(dtpAdmissionDate.getDate());
        student.setGuardian(txtParent.getText());
        student.setRelationship(cmbRelationship.getSelectedItem().toString());
        student.setContactNumber(txtContactNumber.getText());
        student.setSchoolId(((School)cmbSchoolName.getSelectedItem()).getSchoolId());
        student.setClassId(((ClassMaster)cmbClass.getSelectedItem()).getClassMasterId());
        //double feesPercentage = Math.round(Double.parseDouble(txtTuitionFees.getText())*100/gTuitionFees);
        student.setFeesPercentage(Double.parseDouble(txtTuitionFees.getText()));
        student.setExtraCurricular(extraCurricular);

        double dPurchasePrice = 0.0;
        /*(if(chkAddGst.isSelected()){
            dPurchasePrice = Double.parseDouble(txtPurchasePrice.getText())*(1+student.getGstPercentage()/100); 
            System.out.println("--- Purchase Price : "+ dPurchasePrice);            
            System.out.println("After formatingg --"+df.format(dPurchasePrice));
            student.setPurchasePrice(Double.parseDouble(df.format(dPurchasePrice)));
        }*/
        

        StudentDAO studentDAO = new StudentDAO();
        if (studentIdEdit >0){
            student.setStudentId(studentIdEdit);
            studentDAO.updateStudent(student);
        }else
            studentDAO.insertIntoDB(student);
        
    }
    
    public final void fetchDataIntoTable(Student student){
        studentIdEdit=0;
        studentIdEdit = student.getStudentId();
        System.out.println("--Called fetchStockDataIntoTable"+student.getStudentName());
        //initializeForm();
        enableFormElements(true);
        btnSave.setText("Update");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png")));
        
        //--!@09/03/2020
        SchoolDAO schoolDAO = new SchoolDAO();
        renderSupplierDataIntoDropDown(schoolDAO.retrieveAll());
        for(int i=0; i<cmbSchoolName.getItemCount();i++){
            if(((School)cmbSchoolName.getItemAt(i)).getSchoolId()==student.getSchoolId()){
                cmbSchoolName.setSelectedItem(cmbSchoolName.getItemAt(i));
            }
        }
        
        //--!@14/06/2020
        ClassMasterDAO classMasterDAO = new ClassMasterDAO();
        renderCategoryDataIntoDropDown(classMasterDAO.retrieveAll());
        for(int i=0; i<cmbClass.getItemCount();i++){
            if(((ClassMaster)cmbClass.getItemAt(i)).getClassMasterId()==student.getClassId()){
                cmbClass.setSelectedItem(cmbClass.getItemAt(i));
            }
        }
        //cmbSupplier.setSelectedItem(cmbSupplier.getItemAt(3));

        /*GstDAO gstDAO = new GstDAO();
        renderGstDataIntoDropDown(gstDAO.retrieveAll());*/
        //cmbGST.setSelectedItem(student.getGstPercentage());
        /*for(int i=0; i<cmbGST.getItemCount();i++){
            if(((GST)cmbGST.getItemAt(i)).getGstValue()==student.getGstPercentage()){
                cmbGST.setSelectedItem(cmbGST.getItemAt(i));
            }
        }*/
        
        txtParent.setText(student.getGuardian());
        txtStudentName.setText(student.getStudentName());
        dtpAdmissionDate.setDate(student.getAdmissionDate());
        dtpDateOfBirth.setDate(student.getDateOfBirth());
        txtContactNumber.setText(student.getContactNumber());
        txtAddress.setText(student.getAddress());
        if("M".equalsIgnoreCase(student.getGender()))
            radMale.setSelected(true);
        else
            radFemale.setSelected(true);
        if(null!=student.getExtraCurricular()){
            if(student.getExtraCurricular().toLowerCase().contains("singing"))
                chkSinging.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("dancing"))
                chkDancing.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("musicalinstruments"))
                chkMusicalInstruments.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("cricket"))
                chkCricket.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("football"))
                chkFootBall.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("volleyball"))
                chkVolleyBall.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("chess"))
                chkChess.setSelected(true);
            if(student.getExtraCurricular().toLowerCase().contains("others"))
                chkOthers.setSelected(true);
        }
        if(student.getStudentId()>0)
            txtTuitionFees.setText(student.getFeesPercentage()+"");
        /*txtPurchasePrice.setText(student.getPurchasePrice()+"");
        txtMargin.setText(student.getMargin()+"");
        txtQuantity.setText(student.getQuantity()+"");
        txtAddress.setText(student.getDescription());
        txtReOrderAt.setText(student.getReOrderQuantity()+"");
        */
        
        //cmbClass.setSelectedItem(student.getClassId);
        
        

        /*if(salesDetailsModel != null){
        salesDetailsModel.addRow(new Object[]{student.getHsnCode(),student.getItemName(),student.getGstPercentage(),df.format(Double.parseDouble(student.getGstAmount()) * Double.parseDouble(txtQuantity.getText())), itemAmount, Double.parseDouble(txtQuantity.getText()), df.format(itemAmount * Double.parseDouble(txtQuantity.getText())), student.getItemId()});
        //model.
                
        } */
        //deriveValuesFromSalesInput();
    }
    
    public void renderDataIntoTable(List<Supplier> supplierList){
        /*DefaultTableModel supplierModel = null;
        supplierModel = (DefaultTableModel) tblSupplier.getModel();
        System.out.println("-----"+supplierList.size());
        for(int i=0;i<supplierList.size();i++){
        supplierModel.addRow(new Object[]{supplierList.get(i).getSupplierCode(),supplierList.get(i).getSupplierName(),supplierList.get(i).getSupplierContactNumber(), supplierList.get(i).getSupplierRating(), supplierList.get(i).getSupplierAddress()});
        //model.
        }        */
        
    }
    
    
    
    public void renderSupplierDataIntoDropDown(List<School> schoolList){
        School school = null;
        cmbSchoolName.removeAllItems();
        if(schoolList!= null){
            for(int i=0; i<schoolList.size();i++){
                cmbSchoolName.addItem(schoolList.get(i));
            }
            cmbSchoolName.setSelectedIndex(0);
            school = (School)cmbSchoolName.getSelectedItem();            
        }
    }
    
   
    public void renderCategoryDataIntoDropDown(List<ClassMaster> classMasterList){
        ClassMaster classMaster = null;
        cmbClass.removeAllItems();
        if(classMasterList!= null){
            for(int i=0; i<classMasterList.size();i++){
                cmbClass.addItem(classMasterList.get(i));
            }
            cmbClass.setSelectedIndex(0);
            classMaster = (ClassMaster)cmbClass.getSelectedItem();            
        }  
    }
    
    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();
           /* if (menu == mitDelete) {
                //int rowIndex = tblSupplier.getSelectedRow();
                System.out.println("--------INSIDE DELETE-"+tblSupplier.getModel().getValueAt(tblSupplier.getSelectedRow(),0));
                String supplierCode = tblSupplier.getModel().getValueAt(tblSupplier.getSelectedRow(),0).toString();
                SupplierDAO supplierDAO = new SupplierDAO();
                supplierDAO.deleteRecordByCode(supplierCode);
                initializeForm();
            } */
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGender;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JCheckBox chkChess;
    private javax.swing.JCheckBox chkCricket;
    private javax.swing.JCheckBox chkDancing;
    private javax.swing.JCheckBox chkFootBall;
    private javax.swing.JCheckBox chkMusicalInstruments;
    private javax.swing.JCheckBox chkOthers;
    private javax.swing.JCheckBox chkSinging;
    private javax.swing.JCheckBox chkVolleyBall;
    private javax.swing.JComboBox cmbClass;
    private javax.swing.JComboBox cmbRelationship;
    private javax.swing.JComboBox cmbSchoolName;
    private com.toedter.calendar.JDateChooser dtpAdmissionDate;
    private com.toedter.calendar.JDateChooser dtpDateOfBirth;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdmissionDate;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblClass1;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblParent;
    private javax.swing.JLabel lblSchoolName;
    private javax.swing.JPanel pnlStockEntry;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtParent;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtTuitionFees;
    // End of variables declaration//GEN-END:variables
}
